version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=timescale
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=${GF_SERVER_SERVE_FROM_SUB_PATH}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - timescaledb

  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "12345:12345/udp"
    environment:
      - PQ_HOST=${PQ_HOST}
      - PQ_PORT=${PQ_PORT}
      - PQ_USER=${PQ_USER}
      - PQ_PASSWORD=${PQ_PASSWORD}
      - PQ_DBNAME=${PQ_DBNAME}
    restart: always

  caddy:
    image: caddy
    ports:
      - "80:8085"
      - "443:8443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      - server
      - grafana

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports: 
      - "1883:1883"
    volumes: 
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:mosquitto/log"
    restart: always

  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

volumes:
  timescaledb-data:
    driver: local
  grafana_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
