services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=timescale
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: always

  server:
    container_name: server
    build: ./server
    env_file:
      - .env
    ports:
      - "5001:5001"
      - "12345:12345/udp"
    environment:
      - PQ_HOST=${PQ_HOST}
      - PQ_PORT=${PQ_PORT}
      - PQ_USER=${PQ_USER}
      - PQ_PASSWORD=${PQ_PASSWORD}
      - PQ_DBNAME=${PQ_DBNAME}
    restart: always

  caddy:
    container_name: caddy
    image: caddy
    ports:
      - "80:8085"
      - "443:8443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports: 
      - "1883:1883"
    volumes: 
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    restart: always

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080

volumes:
  timescaledb-data:
    driver: local
  grafana_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
