{
 "title": "PicoW Co2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "current co2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM timeseries WHERE (datasource_id = 1 AND metric = 'co2') LIMIT 50 "
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM timeseries WHERE (datasource_id = 1 AND metric = 'temperature') ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "co2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM timeseries WHERE (datasource_id = 1 AND metric = 'co2') ORDER BY \"timestamp\" DESC "
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT value, \"timestamp\" FROM timeseries WHERE (datasource_id = 1 AND metric = 'humidity') ORDER BY \"timestamp\" DESC "
    }
   ]
  }
 ]
}