version: "3.7"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=timescale
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: always

volumes:
  timescaledb-data:
    driver: local
